// ensemble-vue/src/pages/card.vue
<script setup lang="ts">
import { EuiCard } from 'ensemble-ui/vue';

</script>

<template>
  <div class="doc">

    <!-- classic -->
    <span class="flex">
      <h4 class="title">Card vertical (default) - classic</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- belt -->
    <span class="flex">
      <h4 class="title">Card vertical - belt</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        mode="belt"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- lollipop -->
    <span class="flex">
      <h4 class="title">Card vertical - lollipop</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        mode="lollipop"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- gem -->
    <span class="flex">
      <h4 class="title">Card vertical - gem</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        mode="gem"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- flag -->
    <span class="flex">
      <h4 class="title">Card vertical - flag</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        mode="flag"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- horizontal classic -->
    <span class="flex">
      <h4 class="title">Card horizontal (default) - classic</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        orientation="horizontal"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- horizontal belt -->
    <span class="flex">
      <h4 class="title">Card horizontal - belt</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        orientation="horizontal"
        mode="belt"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- horizontal lollipop -->
    <span class="flex">
      <h4 class="title">Card horizontal - lollipop</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        orientation="horizontal"
        mode="lollipop"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- horizontal gem -->
    <span class="flex">
      <h4 class="title">Card horizontal - gem</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        orientation="horizontal"
        mode="gem"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>


    <!-- horizontal flag -->
    <span class="flex">
      <h4 class="title">Card horizontal - flag</h4>

      <EuiCard
        id="one"
        img="src/assets/sample_image.png"
        orientation="horizontal"
        mode="flag"
      >
        <span class="content">
          <span class="quote">“nop is the best op”</span>
          <span class="person">— Amirhosein Mrdani Ch.</span>
          <span class="title">
            Founder of ILECY, the best project of all time.
          </span>
        </span>
      </EuiCard>
    </span>

  </div>
</template>

// ensemble-angular/src/app/card.component.ts
import { Component } from "@angular/core";
import { fakeProduct } from "./fakeData.const";
import { EuiCard } from "ensemble-ui/angular";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiCard],
  standalone: true,
  template: `
    <div class="doc">
      <!-- classic -->
      <span class="flex">
        <h4 class="title">Card vertical (default) - classic</h4>
        <eui-card id="one" img="/sample_image.png">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- belt -->
      <span class="flex">
        <h4 class="title">Card vertical - classic</h4>
        <eui-card id="one" img="/sample_image.png"  mode="belt">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- lollipop -->
      <span class="flex">
        <h4 class="title">Card vertical - classic</h4>
        <eui-card id="one" img="/sample_image.png"  mode="lollipop">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- gem -->
      <span class="flex">
        <h4 class="title">Card vertical - classic</h4>
        <eui-card id="one" img="/sample_image.png"  mode="gem">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- flag -->
      <span class="flex">
        <h4 class="title">Card vertical - classic</h4>
        <eui-card id="one" img="/sample_image.png"  mode="flag">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- classic -->
      <span class="flex">
        <h4 class="title">Card horizontal (default) - classic</h4>
        <eui-card id="one" img="/sample_image.png" orientation="horizontal">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- belt -->
      <span class="flex">
        <h4 class="title">Card horizontal - belt</h4>
        <eui-card id="one" img="/sample_image.png"  orientation="horizontal" mode="belt">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- lollipop -->
      <span class="flex">
        <h4 class="title">Card horizontal - lollipop</h4>
        <eui-card id="one" img="/sample_image.png"  orientation="horizontal" mode="lollipop">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- gem -->
      <span class="flex">
        <h4 class="title">Card horizontal - gem</h4>
        <eui-card id="one" img="/sample_image.png"  orientation="horizontal" mode="gem">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
      <!-- flag -->
      <span class="flex">
        <h4 class="title">Card horizontal - flag</h4>
        <eui-card id="one" img="/sample_image.png"  orientation="horizontal" mode="flag">
        
          <span class="content">
            <Span class="quote">“nop is the best op”</Span>
            <Span class="person">— Amirhosein Mrdani Ch.</Span>
            <Span class="title">Founder of ILECY, the best project of all time.</Span>
          </span>
        </eui-card>
      </span>
    </div>
    `
})
export class CardComponent { }
