// ensemble-vue/src/pages/chips.vue
<script setup lang="ts">
import { EuiChips } from 'ensemble-ui/vue'
import { fakeProduct } from './fakeData.const'

const data = fakeProduct.products

const onProductSelected = (event: CustomEvent) => {
  const product = event.detail

  console.log('Product selected from Vue!', product)
}
</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">Chips by title</h4>

      <EuiChips
        :data="data"
        displayField="title"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>


    <span class="flex">
      <h4 class="title">Chips by dimensions.height</h4>

      <EuiChips
        :data="data"
        displayField="dimensions.height"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>


    <span class="flex">
      <h4 class="title">Chips by reviews.reviewerName</h4>

      <EuiChips
        :data="data"
        displayField="reviews.reviewerName"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>

  </div>
</template>

// ensemble-angular/src/app/chips.component.ts
import { Component } from "@angular/core";
import { FakeDataService } from "./fake.api.service";
import { map } from "rxjs";
import { fakeProduct } from "./fakeData.const";
import { EuiChips } from "ensemble-ui/angular";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiChips],
  standalone: true,
  template: `
    <div class="doc">
      <span class="flex">
        <h4 class="title">Chips by title</h4>
        <eui-chips
          [data]="data"
          displayField="title" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Chips by dimensions.height</h4>
        <eui-chips
          [data]="data"
          displayField="dimensions.height" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Chips by reviews.reviewerName</h4>
        <eui-chips
          [data]="data"
          displayField="reviews.reviewerName" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
    </div>
    `
})
export class ChipsComponent {

  public data = fakeProduct.products;

  /**
   * This method will be called by the (itemSelected) event
   */
  onProductSelected(event: Event) {
    const product = (event as CustomEvent).detail;

    console.log('Product selected from Angular!', product);
    // Now you have the full object:
    // { id: 1, title: "Essence Mascara...", ... }
  }
}
