// ensemble-vue/src/pages/progressbar.vue
<script setup lang="ts">
import { EuiProgressbar } from 'ensemble-ui/vue';

</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">Progressbar - sm:</h4>

      <EuiProgressbar
        styleValue="width:25vw;"
        size="sm"
        :value="0.5"
      />
    </span>


    <span class="flex">
      <h4 class="title">Progressbar - md:</h4>

      <EuiProgressbar
        styleValue="width:25vw;"
        size="md"
        :value="0.5"
      />
    </span>


    <span class="flex">
      <h4 class="title">Progressbar - lg:</h4>

      <EuiProgressbar
        styleValue="width:25vw;"
        size="lg"
        :value="0.5"
      />
    </span>

  </div>
</template>

// ensemble-angular/src/app/progressbar.component.ts
import { Component } from "@angular/core";
import { EuiProgressbar } from "ensemble-ui/angular";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiProgressbar],
  standalone: true,
  template: `
    <div class="doc">
      <span class="flex">
        <h4 class="title">Progressbar - sm:</h4>
       <eui-progressbar styleValue="width:25vw;" size='sm' [value]="0.5"/>
      </span>
      <span class="flex">
        <h4 class="title">Progressbar - md:</h4>
       <eui-progressbar styleValue="width:25vw;" size='md' [value]="0.5"/>
      </span>
      <span class="flex">
        <h4 class="title">Progressbar - lg:</h4>
       <eui-progressbar styleValue="width:25vw;" size='lg' [value]="0.5"/>
      </span>
    </div>
    `
})
export class ProgressbarComponent {
}
