// ensemble-react/src/pages/button.tsx
import { EuiButton } from 'ensemble-ui/react'

export default function ButtonPage() {
  return (
    <div className="doc">
      <span className="flex">
        <h4 className="title">primary - normal buttons:</h4>
        <EuiButton size='sm' variant='primary'>Small Primary</EuiButton>
        <EuiButton size='md' variant='primary'>Medium Primary</EuiButton>
        <EuiButton size='lg' variant='primary'>large Primary</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">success - normal buttons:</h4>
        <EuiButton size='sm' variant='success'>Small success</EuiButton>
        <EuiButton size='md' variant='success'>Medium success</EuiButton>
        <EuiButton size='lg' variant='success'>large success</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">info - normal buttons:</h4>
        <EuiButton size='sm' variant='info'>Small info</EuiButton>
        <EuiButton size='md' variant='info'>Medium info</EuiButton>
        <EuiButton size='lg' variant='info'>large info</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">warning - normal buttons:</h4>
        <EuiButton size='sm' variant='warning'>Small warning</EuiButton>
        <EuiButton size='md' variant='warning'>Medium warning</EuiButton>
        <EuiButton size='lg' variant='warning'>large warning</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">danger - normal buttons:</h4>
        <EuiButton size='sm' variant='danger'>Small danger</EuiButton>
        <EuiButton size='md' variant='danger'>Medium danger</EuiButton>
        <EuiButton size='lg' variant='danger'>large danger</EuiButton>
      </span>
      <span className="divider"></span>
      <span className="flex">
        <h4 className="title">primary - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='primary'>Small Primary</EuiButton>
        <EuiButton mode='outline' size='md' variant='primary'>Medium Primary</EuiButton>
        <EuiButton mode='outline' size='lg' variant='primary'>large Primary</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">success - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='success'>Small success</EuiButton>
        <EuiButton mode='outline' size='md' variant='success'>Medium success</EuiButton>
        <EuiButton mode='outline' size='lg' variant='success'>large success</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">info - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='info'>Small info</EuiButton>
        <EuiButton mode='outline' size='md' variant='info'>Medium info</EuiButton>
        <EuiButton mode='outline' size='lg' variant='info'>large success</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">info - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='info'>Small info</EuiButton>
        <EuiButton mode='outline' size='md' variant='info'>Medium info</EuiButton>
        <EuiButton mode='outline' size='lg' variant='info'>large info</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">warning - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='warning'>Small warning</EuiButton>
        <EuiButton mode='outline' size='md' variant='warning'>Medium warning</EuiButton>
        <EuiButton mode='outline' size='lg' variant='warning'>large warning</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">danger - outline buttons:</h4>
        <EuiButton mode='outline' size='sm' variant='danger'>Small danger</EuiButton>
        <EuiButton mode='outline' size='md' variant='danger'>Medium danger</EuiButton>
        <EuiButton mode='outline' size='lg' variant='danger'>large danger</EuiButton>
      </span>
      <span className="divider"></span>
      <span className="flex">
        <h4 className="title">primary - text-button buttons:</h4>
        <EuiButton mode='text-button' size='sm' variant='primary'>Small Primary</EuiButton>
        <EuiButton mode='text-button' size='md' variant='primary'>Medium Primary</EuiButton>
        <EuiButton mode='text-button' size='lg' variant='primary'>large Primary</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">success - text-button buttons:</h4>
        <EuiButton mode='text-button' size='sm' variant='success'>Small success</EuiButton>
        <EuiButton mode='text-button' size='md' variant='success'>Medium success</EuiButton>
        <EuiButton mode='text-button' size='lg' variant='success'>large success</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">info - text-button buttons:</h4>
        <EuiButton mode='text-button' size='sm' variant='info'>Small info</EuiButton>
        <EuiButton mode='text-button' size='md' variant='info'>Medium info</EuiButton>
        <EuiButton mode='text-button' size='lg' variant='info'>large info</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">warning - text-button buttons:</h4>
        <EuiButton mode='text-button' size='sm' variant='warning'>Small warning</EuiButton>
        <EuiButton mode='text-button' size='md' variant='warning'>Medium warning</EuiButton>
        <EuiButton mode='text-button' size='lg' variant='warning'>large warning</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">danger - text-button buttons:</h4>
        <EuiButton mode='text-button' size='sm' variant='danger'>Small danger</EuiButton>
        <EuiButton mode='text-button' size='md' variant='danger'>Medium danger</EuiButton>
        <EuiButton mode='text-button' size='lg' variant='danger'>large danger</EuiButton>
      </span>
      <span className="flex">
        <h4 className="title">neutral buttons:</h4>
        <EuiButton variant='neutral'>Small neutral</EuiButton>
        <EuiButton variant='neutral'>Medium neutral</EuiButton>
        <EuiButton variant='neutral'>large neutral</EuiButton>
      </span>
      <span className="divider"></span>
      <span className="flex">
        <h4 className="title">primary - text-button buttons:</h4>
        <EuiButton nativeAttrs={{ "disabled": "true" }}>Small Primary</EuiButton>
        <EuiButton nativeAttrs={{ "disabled": "true" }}>Medium Primary</EuiButton>
        <EuiButton nativeAttrs={{ "disabled": "true" }}>large Primary</EuiButton>
      </span>

    </div>
  )
}

// ensemble-vue/src/pages/button.vue
<script setup lang="ts">

import { EuiButton } from 'ensemble-ui/vue'

type ButtonSize = 'sm' | 'md' | 'lg'
type ButtonVariant = 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'neutral'
type ButtonMode = 'normal' | 'outline' | 'text-button'

type ButtonExample = {
  label: string
  size?: ButtonSize
}

type ButtonRow = {
  title: string
  variant?: ButtonVariant
  mode?: ButtonMode
  buttons: ButtonExample[]
}

const normalRows: ButtonRow[] = [
  {
    title: 'primary - normal buttons:',
    variant: 'primary',
    buttons: [
      { label: 'Small Primary', size: 'sm' },
      { label: 'Medium Primary', size: 'md' },
      { label: 'large Primary', size: 'lg' },
    ],
  },
  {
    title: 'success - normal buttons:',
    variant: 'success',
    buttons: [
      { label: 'Small success', size: 'sm' },
      { label: 'Medium success', size: 'md' },
      { label: 'large success', size: 'lg' },
    ],
  },
  {
    title: 'info - normal buttons:',
    variant: 'info',
    buttons: [
      { label: 'Small info', size: 'sm' },
      { label: 'Medium info', size: 'md' },
      { label: 'large info', size: 'lg' },
    ],
  },
  {
    title: 'warning - normal buttons:',
    variant: 'warning',
    buttons: [
      { label: 'Small warning', size: 'sm' },
      { label: 'Medium warning', size: 'md' },
      { label: 'large warning', size: 'lg' },
    ],
  },
  {
    title: 'danger - normal buttons:',
    variant: 'danger',
    buttons: [
      { label: 'Small danger', size: 'sm' },
      { label: 'Medium danger', size: 'md' },
      { label: 'large danger', size: 'lg' },
    ],
  },
]

const outlineRows: ButtonRow[] = [
  {
    title: 'primary - outline buttons:',
    variant: 'primary',
    mode: 'outline',
    buttons: [
      { label: 'Small Primary', size: 'sm' },
      { label: 'Medium Primary', size: 'md' },
      { label: 'large Primary', size: 'lg' },
    ],
  },
  {
    title: 'success - outline buttons:',
    variant: 'success',
    mode: 'outline',
    buttons: [
      { label: 'Small success', size: 'sm' },
      { label: 'Medium success', size: 'md' },
      { label: 'large success', size: 'lg' },
    ],
  },
  {
    title: 'info - outline buttons:',
    variant: 'info',
    mode: 'outline',
    buttons: [
      { label: 'Small info', size: 'sm' },
      { label: 'Medium info', size: 'md' },
      { label: 'large success', size: 'lg' },
    ],
  },
  {
    title: 'info - outline buttons:',
    variant: 'info',
    mode: 'outline',
    buttons: [
      { label: 'Small info', size: 'sm' },
      { label: 'Medium info', size: 'md' },
      { label: 'large info', size: 'lg' },
    ],
  },
  {
    title: 'warning - outline buttons:',
    variant: 'warning',
    mode: 'outline',
    buttons: [
      { label: 'Small warning', size: 'sm' },
      { label: 'Medium warning', size: 'md' },
      { label: 'large warning', size: 'lg' },
    ],
  },
  {
    title: 'danger - outline buttons:',
    variant: 'danger',
    mode: 'outline',
    buttons: [
      { label: 'Small danger', size: 'sm' },
      { label: 'Medium danger', size: 'md' },
      { label: 'large danger', size: 'lg' },
    ],
  },
]

const textButtonRows: ButtonRow[] = [
  {
    title: 'primary - text-button buttons:',
    variant: 'primary',
    mode: 'text-button',
    buttons: [
      { label: 'Small Primary', size: 'sm' },
      { label: 'Medium Primary', size: 'md' },
      { label: 'large Primary', size: 'lg' },
    ],
  },
  {
    title: 'success - text-button buttons:',
    variant: 'success',
    mode: 'text-button',
    buttons: [
      { label: 'Small success', size: 'sm' },
      { label: 'Medium success', size: 'md' },
      { label: 'large success', size: 'lg' },
    ],
  },
  {
    title: 'info - text-button buttons:',
    variant: 'info',
    mode: 'text-button',
    buttons: [
      { label: 'Small info', size: 'sm' },
      { label: 'Medium info', size: 'md' },
      { label: 'large info', size: 'lg' },
    ],
  },
  {
    title: 'warning - text-button buttons:',
    variant: 'warning',
    mode: 'text-button',
    buttons: [
      { label: 'Small warning', size: 'sm' },
      { label: 'Medium warning', size: 'md' },
      { label: 'large warning', size: 'lg' },
    ],
  },
  {
    title: 'danger - text-button buttons:',
    variant: 'danger',
    mode: 'text-button',
    buttons: [
      { label: 'Small danger', size: 'sm' },
      { label: 'Medium danger', size: 'md' },
      { label: 'large danger', size: 'lg' },
    ],
  },
]

const neutralButtons: ButtonExample[] = [
  { label: 'Small neutral' },
  { label: 'Medium neutral' },
  { label: 'large neutral' },
]

const disabledButtons = ['Small Primary', 'Medium Primary', 'large Primary']
</script>

<template>
  <section class="doc" aria-label="Button documentation">
    <div v-for="row in normalRows" :key="row.title" class="flex">
      <h4 class="title">{{ row.title }}</h4>
      <EuiButton v-for="button in row.buttons" :key="button.label" :size="button.size" :variant="row.variant"
        :mode="row.mode">
        {{ button.label }}
      </EuiButton>
    </div>

    <div class="divider" />

    <div v-for="(row, index) in outlineRows" :key="`${row.title}-${index}`" class="flex">
      <h4 class="title">{{ row.title }}</h4>
      <EuiButton v-for="button in row.buttons" :key="button.label" :size="button.size" :variant="row.variant"
        :mode="row.mode">
        {{ button.label }}
      </EuiButton>
    </div>

    <div class="divider" />

    <div v-for="row in textButtonRows" :key="row.title" class="flex">
      <h4 class="title">{{ row.title }}</h4>
      <EuiButton v-for="button in row.buttons" :key="button.label" :size="button.size" :variant="row.variant"
        :mode="row.mode">
        {{ button.label }}
      </EuiButton>
    </div>

    <div class="flex">
      <h4 class="title">neutral buttons:</h4>
      <EuiButton v-for="button in neutralButtons" :key="button.label" variant="neutral">
        {{ button.label }}
      </EuiButton>
    </div>

    <div class="divider" />

    <div class="flex">
      <h4 class="title">primary - text-button buttons:</h4>
      <EuiButton v-for="label in disabledButtons" :key="label" :disabled="true">{{ label }}</EuiButton>
    </div>
  </section>
</template>
