// ensemble-react/src/pages/datepicker.tsx
import { EuiDatepicker } from 'ensemble-ui/react'

export default function DatepickerPage() {
  const date = new Date()

  const onDateSelected = (event: CustomEvent) => {
    const selectedDate = event.detail

    console.log('Date selected from React!', selectedDate)
  }

  return (
    <div
      className="doc"
      style={{ height: '30vh' }}
    >
      <span className="flex">
        <h4 className="title">Basic datepicker</h4>

        <EuiDatepicker
          date={date}
          onDateChanged={onDateSelected}
          styleValue="width: 25vw;"
        />
      </span>
    </div>
  )
}

// ensemble-vue/src/pages/datepicker.vue
<script setup lang="ts">
import { EuiDatepicker } from 'ensemble-ui/vue';

const date = new Date()

const onDateSelected = (event: CustomEvent) => {
  const selectedDate = event.detail

  console.log('Date selected from Vue!', selectedDate)
}
</script>

<template>
  <div
    class="doc"
    style="height: 30vh"
  >
    <span class="flex">
      <h4 class="title">Basic datepicker</h4>

      <EuiDatepicker
        :date="date"
        @dateChanged="onDateSelected"
        styleValue="width: 25vw;"
      />
    </span>
  </div>
</template>
