// ensemble-angular/src/app/datepicker.component.ts
import { Component } from "@angular/core";
import { fakeProduct } from "./fakeData.const";
import { EuiDatepicker } from "ensemble-ui/angular";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiDatepicker],
  standalone: true,
  template: `
    <div class="doc" style="height: 30vh;">
      <span class="flex">
        <h4 class="title">Basic datepicker</h4>
        <eui-datepicker
          [date]="date"
          (dateChanged)="onDateSelected($event)"
          styleValue="width: 25vw;"
        />
      </span>
    </div>
    `
})
export class DatepickerComponent {

  public date = new Date();

  /**
   * This method will be called by the (itemSelected) event
   */
  onDateSelected(event: Event) {

  }
}

// ensemble-vue/src/pages/datepicker.vue
<script setup lang="ts">
import { EuiDatepicker } from 'ensemble-ui/vue';

const date = new Date()

const onDateSelected = (event: CustomEvent) => {
  const selectedDate = event.detail

  console.log('Date selected from Vue!', selectedDate)
}
</script>

<template>
  <div
    class="doc"
    style="height: 30vh"
  >
    <span class="flex">
      <h4 class="title">Basic datepicker</h4>

      <EuiDatepicker
        :date="date"
        @dateChanged="onDateSelected"
        styleValue="width: 25vw;"
      />
    </span>
  </div>
</template>
