// ensemble-react/src/pages/sidenav.tsx
import {
  EuiButton,
  EuiCheckbox,
  EuiIcon,
  EuiInput,
  EuiSideNav,
} from 'ensemble-ui/react'

export default function SideNavPage() {
  return (
    <div className="doc">

      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - full - center:
        </h4>

        <span className="side-nav-holder">
          <EuiSideNav>
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">Home</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">Search</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">Explore</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">Cart</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">Wallet</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">Sign out</span>
              </div>
            </div>
          </EuiSideNav>

          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>
        </span>
      </span>


      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - full - top:
        </h4>

        <span className="side-nav-holder">
          <EuiSideNav mode="start">
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">Home</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">Search</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">Explore</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">Cart</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">Wallet</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">Sign out</span>
              </div>
            </div>
          </EuiSideNav>

          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>
        </span>
      </span>


      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - compact - top:
        </h4>

        <span className="side-nav-holder">
          <EuiSideNav size="compact">
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">Home</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">Search</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">Explore</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">Cart</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">Wallet</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">Sign out</span>
              </div>
            </div>
          </EuiSideNav>

          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>
        </span>
      </span>


      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - full - center - rtl:
        </h4>

        <span className="side-nav-holder">
          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>

          <EuiSideNav direction="rtl">
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">خانه</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">جستجو</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">اکسپلور</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">سبد خرید</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">کیف پول</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">خروج</span>
              </div>
            </div>
          </EuiSideNav>
        </span>
      </span>


      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - full - top:
        </h4>

        <span className="side-nav-holder">
          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>

          <EuiSideNav mode="start" direction="rtl">
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">خانه</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">جستجو</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">اکسپلور</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">سبد خرید</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">کیف پول</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">خروج</span>
              </div>
            </div>
          </EuiSideNav>
        </span>
      </span>


      <span className="flex flex-col">
        <h4 className="title w-80 justify-start flex">
          Side nav - compact - top:
        </h4>

        <span className="side-nav-holder">
          <div className="simulator flex">
            <div className="header flex">
              <span className="user flex">
                <EuiIcon name="user-circle" type="outline" />
                <div className="welcome">Hi, Amirhosein!</div>
              </span>

              <div className="welcome">Your wallet: 22.18$</div>
            </div>

            <div className="body">
              <span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>
                <span><EuiInput nativeAttrs={{ "placeHolder": "simple input"}} type="password" /></span>
                <span><EuiInput type="number" nativeAttrs={{ "placeHolder": "simple input"}} /></span>

                <span className="checkbox-boy">
                  <EuiCheckbox
                    states={["null" , "false" , "partial" , "true"]}
                    size="lg"
                    mode="outline"
                  />
                  Include wallet
                </span>
              </span>

              <span>
                <EuiButton mode="outline" size="md" variant="primary">
                  Order
                </EuiButton>
              </span>
            </div>
          </div>

          <EuiSideNav size="compact" direction="rtl">
            <div slot="top">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="home" />
                <span className="text">خانه</span>
              </div>
            </div>

            <div slot="middle">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="magnifying-glass" />
                <span className="text">جستجو</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="globe-americas" />
                <span className="text">اکسپلور</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="shopping-cart" />
                <span className="text">سبد خرید</span>
              </div>

              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="wallet" />
                <span className="text">کیف پول</span>
              </div>
            </div>

            <div slot="bottom">
              <div className="item">
                <EuiIcon style={{ width: '24px' }} name="power" />
                <span className="text">خروج</span>
              </div>
            </div>
          </EuiSideNav>
        </span>
      </span>

    </div>
  )
}

// ensemble-vue/src/pages/sidenav.vue
<script setup lang="ts">
import { EuiSideNav } from 'ensemble-ui/vue';

</script>

<template>
  <div class="doc">

    <!-- ========================================================= -->
    <!-- FULL - CENTER                                             -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - full - center:
      </h4>

      <span class="side-nav-holder">

        <EuiSideNav>

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">Home</span>
            </div>
          </div>

          <div slot="middle">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">Search</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">Explore</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">Cart</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">Wallet</span>
            </div>
          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">Sign out</span>
            </div>
          </div>

        </EuiSideNav>


        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  type="number"
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  type="number"
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  type="password"
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span>
                <eui-input
                  type="number"
                  :nativeAttrs="{ placeHolder: 'simple input' }"
                />
              </span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>

      </span>
    </span>


    <!-- ========================================================= -->
    <!-- FULL - TOP                                                -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - full - top:
      </h4>

      <span class="side-nav-holder">

        <EuiSideNav mode="start">

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">Home</span>
            </div>
          </div>

          <div slot="middle">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">Search</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">Explore</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">Cart</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">Wallet</span>
            </div>
          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">Sign out</span>
            </div>
          </div>

        </EuiSideNav>


        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="password" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>

      </span>
    </span>


    <!-- ========================================================= -->
    <!-- COMPACT - TOP                                             -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - compact - top:
      </h4>

      <span class="side-nav-holder">

        <EuiSideNav size="compact">

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">Home</span>
            </div>
          </div>

          <div slot="middle">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">Search</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">Explore</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">Cart</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">Wallet</span>
            </div>
          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">Sign out</span>
            </div>
          </div>

        </EuiSideNav>


        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="password" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>

      </span>
    </span>


    <!-- ========================================================= -->
    <!-- FULL - CENTER - RTL                                       -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - full - center - rtl:
      </h4>

      <span class="side-nav-holder">

        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="password" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>


        <EuiSideNav direction="rtl">

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">خانه</span>
            </div>
          </div>

          <div slot="middle">

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">جستجو</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">اکسپلور</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">سبد خرید</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">کیف پول</span>
            </div>

          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">خروج</span>
            </div>
          </div>

        </EuiSideNav>

      </span>
    </span>


    <!-- ========================================================= -->
    <!-- FULL - TOP - RTL                                         -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - full - top:
      </h4>

      <span class="side-nav-holder">

        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="password" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>


        <EuiSideNav
          mode="start"
          direction="rtl"
        >

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">خانه</span>
            </div>
          </div>

          <div slot="middle">

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">جستجو</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">اکسپلور</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">سبد خرید</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">کیف پول</span>
            </div>

          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">خروج</span>
            </div>
          </div>

        </EuiSideNav>

      </span>
    </span>


    <!-- ========================================================= -->
    <!-- COMPACT - TOP - RTL                                      -->
    <!-- ========================================================= -->

    <span class="flex flex-col">
      <h4 class="title w-80 justify-start flex">
        Side nav - compact - top:
      </h4>

      <span class="side-nav-holder">

        <div class="simulator flex">

          <div class="header flex">
            <span class="user flex">
              <eui-icon name="user-circle" type="outline" />
              <div class="welcome">Hi, Amirhosein!</div>
            </span>

            <div class="welcome">Your wallet: 22.18$</div>
          </div>

          <div class="body">

            <span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="password" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>
              <span><eui-input type="number" :nativeAttrs="{ placeHolder: 'simple input' }" /></span>

              <span class="checkbox-boy">
                <eui-checkbox
                  :states="['null', 'false', 'partial', 'true']"
                  size="lg"
                  mode="outline"
                />
                Include wallet
              </span>
            </span>

            <span>
              <eui-button
                mode="outline"
                size="md"
                variant="primary"
              >
                Order
              </eui-button>
            </span>

          </div>
        </div>


        <EuiSideNav
          size="compact"
          direction="rtl"
        >

          <div slot="top">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="home" />
              <span class="text">خانه</span>
            </div>
          </div>

          <div slot="middle">

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="magnifying-glass" />
              <span class="text">جستجو</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="globe-americas" />
              <span class="text">اکسپلور</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="shopping-cart" />
              <span class="text">سبد خرید</span>
            </div>

            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="wallet" />
              <span class="text">کیف پول</span>
            </div>

          </div>

          <div slot="bottom">
            <div class="item">
              <eui-icon :style="{ width: '24px' }" name="power" />
              <span class="text">خروج</span>
            </div>
          </div>

        </EuiSideNav>

      </span>
    </span>

  </div>
</template>
