// ensemble-react/src/pages/toggle.tsx
import { EuiToggle } from 'ensemble-ui/react'

export default function TogglePage() {
  const data = [
    { text: 'All', icon: 'archive-box-arrow-down' },
    { text: 'Unread', icon: 'adjustments-vertical' },
    { text: 'Favorites', icon: 'arrow-down' },
    { text: 'Archived', icon: 'bookmark' },
  ]

  return (
    <div className="doc">

      <span className="flex">
        <h4 className="title">Toggle:</h4>

        <EuiToggle
          value={1}
          data={data}
        />
      </span>

      <span className="flex">
        <h4 className="title">Toggle - disabled:</h4>

        <EuiToggle
          disabled
          value={2}
          data={data}
        />
      </span>

    </div>
  )
}

// ensemble-vue/src/pages/toggle.vue
<script setup lang="ts">
import { EuiToggle } from 'ensemble-ui/vue';

const data = [
  { text: 'All', icon: 'archive-box-arrow-down' },
  { text: 'Unread', icon: 'adjustments-vertical' },
  { text: 'Favorites', icon: 'arrow-down' },
  { text: 'Archived', icon: 'bookmark' },
]
</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">Toggle:</h4>

      <EuiToggle
        :value="1"
        :data="data"
      />
    </span>

    <span class="flex">
      <h4 class="title">Toggle - disabled:</h4>

      <EuiToggle
        disabled
        :value="2"
        :data="data"
      />
    </span>

  </div>
</template>
