// ensemble-angular/src/app/autocomplete.component.ts
import { Component } from "@angular/core";
import { FakeDataService } from "./fake.api.service";
import { map } from "rxjs";
import { EuiAutoComplete } from "ensemble-ui/angular";


@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiAutoComplete],
  standalone: true,
  template: `
    <div class="doc">
      <span class="flex">
        <h4 class="title">autocomplete example</h4>
        <eui-auto-complete
          [fetchSuggestions]="fetchSuggestions"
          displayField="title" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
    </div>
    `
})
export class AutoCompleteComponent {

  constructor(private fakeApi: FakeDataService) { }

  // This is now much cleaner!
  fetchSuggestions = (query: string) => {


    this.fakeApi.getProductsDummy().subscribe(d => {

      console.log(d);
    })

    return this.fakeApi.getProductsDummy()
      .pipe(
        map(response => {
          if (!query || query.trim() === '') {
            return [];
          }
          // The filtering is happening here!
          return response.products.filter((product: any) =>
            product.title.toLowerCase().includes(query.toLowerCase())
          );
        })
      )
      .toPromise();
  };

  /**
   * This method will be called by the (itemSelected) event
   */
  onProductSelected(event: Event) {
    const product = (event as CustomEvent).detail;

    console.log('Product selected from Angular!', product);
    // Now you have the full object:
    // { id: 1, title: "Essence Mascara...", ... }
  }
}

// ensemble-react/src/pages/autocomplete.tsx
import { EuiAutoComplete } from 'ensemble-ui/react'

type Product = {
  id: number
  title: string
  [key: string]: unknown
}

type ProductsResponse = {
  products: Product[]
}

export default function AutoCompletePage() {

  const fetchSuggestions = async (query: string): Promise<Product[]> => {
    if (!query || query.trim() === '') {
      return []
    }

    const response = await fetch('https://dummyjson.com/products')
    const data: ProductsResponse = await response.json()

    return data.products.filter(product =>
      product.title.toLowerCase().includes(query.toLowerCase())
    )
  }

  const onProductSelected = (event: CustomEvent<Product>) => {
    const product = event.detail

    console.log('Product selected from React!', product)
  }

  return (
    <div className="doc">
      <span className="flex">
        <h4 className="title">autocomplete example</h4>

        <EuiAutoComplete
          fetchSuggestions={fetchSuggestions}
          displayField="title"
          onItemSelected={onProductSelected}
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
    </div>
  )
}
