// ensemble-vue/src/pages/paginator.vue
<script setup lang="ts">
import { EuiPaginator } from 'ensemble-ui/vue';
import { ref } from 'vue'

const currentPage = ref(5)

const onPageChange = (event: CustomEvent<number>) => {
  currentPage.value = event.detail
}
</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">Simple Input</h4>

      <EuiPaginator
        :totalPages="10"
        :defaultCurrentPage="currentPage"
        @currentPage="onPageChange"
      />

      <span>current page: {{ currentPage }}</span>
    </span>


    <span class="flex">
      <h4 class="title">Simple Input</h4>

      <EuiPaginator
        :totalPages="10"
        :defaultCurrentPage="currentPage"
        :disabled="true"
      />
    </span>

  </div>
</template>

// ensemble-react/src/pages/paginator.tsx
import { useState } from 'react'
import { EuiPaginator } from 'ensemble-ui/react'

export default function PaginatorPage() {
  const [currentPage, setCurrentPage] = useState(5)

  const onPageChange = (event: CustomEvent<number>) => {
    setCurrentPage(event.detail)
  }

  return (
    <div className="doc">

      <span className="flex">
        <h4 className="title">Simple Input</h4>

        <EuiPaginator
          totalPages={10}
          defaultCurrentPage={currentPage}
          onCurrentPage={onPageChange}
        />

        <span>current page: {currentPage}</span>
      </span>


      <span className="flex">
        <h4 className="title">Simple Input</h4>

        <EuiPaginator
          totalPages={10}
          defaultCurrentPage={currentPage}
          nativeAttrs={{
            "disabled": "true",
          }}
        />
      </span>

    </div>
  )
}
