// ensemble-vue/src/pages/snackbar.vue
<script setup lang="ts">
import { EuiButton, EuiSnackbar } from 'ensemble-ui/vue'
import { ref } from 'vue'

const open = ref<boolean[]>(
  Array(13).fill(false)
)

const showSnackbar = (index: number) => {
  const next = [...open.value]
  next[index] = true
  open.value = next
}
</script>

<template>
  <div class="doc">

    <!-- Light / Info -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(1)" mode="text-button" variant="info">
        light
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[1]" @dismissing="open[1] = false" :awake-time="3000" :dismiss="false" variant="info"
          message="Lorem Ipsum is simply dummy text..." />
      </span>
    </span>


    <!-- Light / Warning -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(2)" mode="text-button" variant="warning">
        light
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[2]" @dismissing="open[2] = false" :awake-time="3000" :dismiss="false"
          variant="warning" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Light / Danger -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(3)" mode="text-button" variant="danger">
        light
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[3]" @dismissing="open[3] = false" :awakeTime="3000" :dismiss="false" variant="danger"
          message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Light / Success -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(4)" mode="text-button" variant="success">
        light
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[4]" @dismissing="open[4] = false" :awakeTime="3000" :dismiss="false" variant="success"
          message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <span class="flex" />


    <!-- Header / Info -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(5)" mode="text-button" variant="info">
        Header
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[5]" @dismissing="open[5] = false" :awakeTime="3000" :dismiss="false" variant="info"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Warning -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(6)" mode="text-button" variant="warning">
        Header
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[6]" @dismissing="open[6] = false" :awakeTime="3000" :dismiss="false" variant="warning"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Danger -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(7)" mode="text-button" variant="danger">
        Header
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[7]" @dismissing="open[7] = false" :awakeTime="3000" :dismiss="false" variant="danger"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Success -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(8)" mode="text-button" variant="success">
        Header
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[8]" @dismissing="open[8] = false" :awakeTime="3000" :dismiss="false" variant="success"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <span class="flex" />


    <!-- Header / Dismiss / Info -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(9)" mode="text-button" variant="info">
        Header - dissmiss
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[9]" :awakeTime="3000" :dismiss="true" variant="info" @dismissing="open[9] = false"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Dismiss / Warning -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(10)" mode="text-button" variant="warning">
        Header - dissmiss
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[10]" @dismissing="open[10] = false" :awakeTime="3000" :dismiss="true"
          variant="warning" header="New Update!"
          message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Dismiss / Danger -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(11)" mode="text-button" variant="danger">
        Header - dissmiss
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[11]" @dismissing="open[11] = false" :awakeTime="3000" :dismiss="true" variant="danger"
          header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>


    <!-- Header / Dismiss / Success -->
    <span class="flex" style="width: 50vw">
      <EuiButton @click="showSnackbar(12)" mode="text-button" variant="success">
        Header - dissmiss
      </EuiButton>

      <span class="snackbar-container" style="width: 100%">
        <EuiSnackbar :open="open[12]" @dismissing="open[12] = false" :awakeTime="3000" :dismiss="true"
          variant="success" header="New Update!"
          message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
      </span>
    </span>

  </div>
</template>

// ensemble-react/src/pages/snackbar.tsx
import { useState } from 'react'
import { EuiButton, EuiSnackbar } from 'ensemble-ui/react'

export default function SnackbarPage() {
  const [open, setOpen] = useState<boolean[]>(
    Array(13).fill(false)
  )

  const showSnackbar = (index: number) => {
    setOpen(current => {
      const next = [...current]
      next[index] = true
      return next
    })
  }

  return (
    <div className="doc">

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(1)}
          mode="text-button"
          variant="info"
        >
          light
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[1]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 1 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="info" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(2)}
          mode="text-button"
          variant="warning"
        >
          light
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[2]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 2 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="warning" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(3)}
          mode="text-button"
          variant="danger"
        >
          light
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[3]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 3 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="danger" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(4)}
          mode="text-button"
          variant="success"
        >
          light
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[4]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 4 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="success" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" />

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(5)}
          mode="text-button"
          variant="info"
        >
          Header
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[5]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 5 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="info" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(6)}
          mode="text-button"
          variant="warning"
        >
          Header
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[6]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 6 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="warning" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(7)}
          mode="text-button"
          variant="danger"
        >
          Header
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[7]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 7 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="danger" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(8)}
          mode="text-button"
          variant="success"
        >
          Header
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[8]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 8 ? false : value)
              )
            }
            awake-time={3000} dismiss={false} variant="success" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" />

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(9)}
          mode="text-button"
          variant="info"
        >
          Header - dissmiss
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[9]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 9 ? false : value)
              )
            }
            awake-time={3000} dismiss={true} variant="info" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(10)}
          mode="text-button"
          variant="warning"
        >
          Header - dissmiss
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[10]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 10 ? false : value)
              )
            }
            awake-time={3000} dismiss={true} variant="warning" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(11)}
          mode="text-button"
          variant="danger"
        >
          Header - dissmiss
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[11]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 11 ? false : value)
              )
            }
            awake-time={3000} dismiss={true} variant="danger" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

      <span className="flex" style={{ width: '50vw' }}>
        <EuiButton
          onClick={() => showSnackbar(12)}
          mode="text-button"
          variant="success"
        >
          Header - dissmiss
        </EuiButton>

        <span className="snackbar-container" style={{ width: '100%' }}>
          <EuiSnackbar open={open[12]}
            onDismissing={() =>
              setOpen(current =>
                current.map((value, index) => index === 12 ? false : value)
              )
            }
            awake-time={3000} dismiss={true} variant="success" header="New Update!" message="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        </span>
      </span>

    </div>
  )
}
