// ensemble-angular/src/app/stepper.component.ts
import { Component } from "@angular/core";
import { EuiButton, EuiStepper } from "ensemble-ui/angular";

@Component({
    selector: 'app-root',
    styleUrl: './app.scss',
    imports: [EuiStepper, EuiButton],
    standalone: true,
    template: `
    <div class="doc">
        <span class="flex flex-col">
            <h4 class="title">Stepper - horizontal:</h4>
            <span class="stepper-wrapper">
                <eui-stepper (stepSelect)="selected($event.detail)" [steps]="value" [currentStep]="currentStep"/> 
            </span>
        </span>
        <span class="flex flex-col">
            <h4 class="title">Stepper - vertical:</h4>
            <span class="stepper-wrapper vertical">
                <eui-stepper (stepSelect)="selected($event.detail)" orientation='vertical' [steps]="value" [currentStep]="currentStep"/> 
            </span>
            <span class="flex justify-between w-80">
                <eui-button (click)="change(-1)" mode='outline' size='sm' variant='info'>Previous</eui-button>
                <eui-button (click)="change(+1)" mode='outline' size='sm' variant='info'>Next</eui-button>
            </span>
        </span>
    </div>
    `
})
export class StepperComponent {
    value = ['Select flight', 'Passengers', 'Travel info', 'Payment method', 'Finalize'];
    currentStep = 0;

    change(value: number) {
        let v = this.currentStep + value;
        if (this.currentStep + value > this.value.length) v = this.value.length;
        else if (this.currentStep + value < 0) v = 0;

        this.currentStep = v
    }

    selected(e: number) {
        this.currentStep = e;
    }
}

// ensemble-react/src/pages/stepper.tsx
import { useState } from 'react'
import { EuiButton, EuiStepper } from 'ensemble-ui/react'

export default function StepperPage() {
  const steps = [
    'Select flight',
    'Passengers',
    'Travel info',
    'Payment method',
    'Finalize',
  ]

  const [currentStep, setCurrentStep] = useState(0)

  const change = (value: number) => {
    let next = currentStep + value

    if (next > steps.length) {
      next = steps.length
    } else if (next < 0) {
      next = 0
    }

    setCurrentStep(next)
  }

  const selected = (step: number) => {
    setCurrentStep(step)
  }

  return (
    <div className="doc">

      <span className="flex flex-col">
        <h4 className="title">Stepper - horizontal:</h4>

        <span className="stepper-wrapper">
          <EuiStepper
            onStepSelect={(event) => selected(event.detail)}
            steps={steps}
            currentStep={currentStep}
          />
        </span>
      </span>

      <span className="flex flex-col">
        <h4 className="title">Stepper - vertical:</h4>

        <span className="stepper-wrapper vertical">
          <EuiStepper
            onStepSelect={(event) => selected(event.detail)}
            orientation="vertical"
            steps={steps}
            currentStep={currentStep}
          />
        </span>

        <span className="flex justify-between w-80">
          <EuiButton
            onClick={() => change(-1)}
            mode="outline"
            size="sm"
            variant="info"
          >
            Previous
          </EuiButton>

          <EuiButton
            onClick={() => change(1)}
            mode="outline"
            size="sm"
            variant="info"
          >
            Next
          </EuiButton>
        </span>
      </span>

    </div>
  )
}
