// ensemble-vue/src/pages/stepper.vue
<script setup lang="ts">
import { ref } from 'vue'
import { EuiButton, EuiStepper } from 'ensemble-ui/vue'

const steps = [
  'Select flight',
  'Passengers',
  'Travel info',
  'Payment method',
  'Finalize',
]

const currentStep = ref(0)

const change = (value: number) => {
  let next = currentStep.value + value

  if (next > steps.length) {
    next = steps.length
  } else if (next < 0) {
    next = 0
  }

  currentStep.value = next
}

const selected = (step: number) => {
  currentStep.value = step
}

const onStepSelect = (event: CustomEvent<number>) => {
  selected(event.detail)
}
</script>

<template>
  <div class="doc">

    <span class="flex flex-col">
      <h4 class="title">Stepper - horizontal:</h4>

      <span class="stepper-wrapper">
        <EuiStepper
          :steps="steps"
          :current-step="currentStep"
          @step-select="onStepSelect"
        />
      </span>
    </span>


    <span class="flex flex-col">
      <h4 class="title">Stepper - vertical:</h4>

      <span class="stepper-wrapper vertical">
        <EuiStepper
          :steps="steps"
          :current-step="currentStep"
          orientation="vertical"
          @step-select="onStepSelect"
        />
      </span>

      <span class="flex justify-between w-80">
        <EuiButton
          @click="change(-1)"
          mode="outline"
          size="sm"
          variant="info"
        >
          Previous
        </EuiButton>

        <EuiButton
          @click="change(1)"
          mode="outline"
          size="sm"
          variant="info"
        >
          Next
        </EuiButton>
      </span>
    </span>

  </div>
</template>

// ensemble-react/src/pages/stepper.tsx
import { useState } from 'react'
import { EuiButton, EuiStepper } from 'ensemble-ui/react'

export default function StepperPage() {
  const steps = [
    'Select flight',
    'Passengers',
    'Travel info',
    'Payment method',
    'Finalize',
  ]

  const [currentStep, setCurrentStep] = useState(0)

  const change = (value: number) => {
    let next = currentStep + value

    if (next > steps.length) {
      next = steps.length
    } else if (next < 0) {
      next = 0
    }

    setCurrentStep(next)
  }

  const selected = (step: number) => {
    setCurrentStep(step)
  }

  return (
    <div className="doc">

      <span className="flex flex-col">
        <h4 className="title">Stepper - horizontal:</h4>

        <span className="stepper-wrapper">
          <EuiStepper
            onStepSelect={(event) => selected(event.detail)}
            steps={steps}
            currentStep={currentStep}
          />
        </span>
      </span>

      <span className="flex flex-col">
        <h4 className="title">Stepper - vertical:</h4>

        <span className="stepper-wrapper vertical">
          <EuiStepper
            onStepSelect={(event) => selected(event.detail)}
            orientation="vertical"
            steps={steps}
            currentStep={currentStep}
          />
        </span>

        <span className="flex justify-between w-80">
          <EuiButton
            onClick={() => change(-1)}
            mode="outline"
            size="sm"
            variant="info"
          >
            Previous
          </EuiButton>

          <EuiButton
            onClick={() => change(1)}
            mode="outline"
            size="sm"
            variant="info"
          >
            Next
          </EuiButton>
        </span>
      </span>

    </div>
  )
}
