// ensemble-vue/src/pages/autocomplete.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'

type Product = {
  id: number
  title: string
  [key: string]: unknown
}

type ProductsResponse = {
  products: Product[]
}

type AutoCompleteElement = HTMLElement & {
  displayField?: string
  fetchSuggestions?: (query: string) => Promise<Product[]>
  styleValue?: string
}

const autoComplete = ref<AutoCompleteElement>()

async function fetchSuggestions(query: string): Promise<Product[]> {
  if (!query || query.trim() === '') {
    return []
  }

  const response = await fetch('https://dummyjson.com/products')
  const data: ProductsResponse = await response.json()

  return data.products.filter((product) =>
    product.title.toLowerCase().includes(query.toLowerCase()),
  )
}

function onProductSelected(event: Event) {
  const product = (event as CustomEvent<Product>).detail

  console.log('Product selected from Vue!', product)
}

onMounted(() => {
  const element = autoComplete.value

  if (!element) {
    return
  }

  element.fetchSuggestions = fetchSuggestions
  element.displayField = 'title'
  element.styleValue = 'width: 25vw;'
  element.addEventListener('itemSelected', onProductSelected)
})

onBeforeUnmount(() => {
  autoComplete.value?.removeEventListener('itemSelected', onProductSelected)
})
</script>

<template>
  <section class="doc" aria-label="Autocomplete documentation">
    <div class="flex">
      <h4 class="title">autocomplete example</h4>

      <eui-auto-complete ref="autoComplete" placeholder="Search products..." />
    </div>
  </section>
</template>

// ensemble-angular-web/src/app/autocomplete.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
import { FakeDataService } from "./fake.api.service";
import { map } from "rxjs";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  standalone: true,
  template: `
    <div class="doc">
      <span class="flex">
        <h4 class="title">autocomplete example</h4>
        <eui-auto-complete
          [fetchSuggestions]="fetchSuggestions"
          displayField="title" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
    </div>
    `
})
export class AutoCompleteComponent {

  constructor(private fakeApi: FakeDataService) { }

  // This is now much cleaner!
  fetchSuggestions = (query: string) => {


    this.fakeApi.getProductsDummy().subscribe(d => {

      console.log(d);
    })

    return this.fakeApi.getProductsDummy()
      .pipe(
        map(response => {
          if (!query || query.trim() === '') {
            return [];
          }
          // The filtering is happening here!
          return response.products.filter((product: any) =>
            product.title.toLowerCase().includes(query.toLowerCase())
          );
        })
      )
      .toPromise();
  };

  /**
   * This method will be called by the (itemSelected) event
   */
  onProductSelected(event: Event) {
    const product = (event as CustomEvent).detail;

    console.log('Product selected from Angular!', product);
    // Now you have the full object:
    // { id: 1, title: "Essence Mascara...", ... }
  }
}
