// ensemble-vue/src/pages/dropdown.vue
<script setup lang="ts">
import { fakeProduct } from './fakeData.const'

const data = fakeProduct.products

const onProductSelected = (event: CustomEvent) => {
  const product = event.detail

  console.log('Product selected from Vue!', product)
}
</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">Dropdown by title</h4>

      <eui-dropdown
        :data="data"
        displayField="title"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>


    <span class="flex">
      <h4 class="title">Dropdown by dimensions.height</h4>

      <eui-dropdown
        :data="data"
        displayField="dimensions.height"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>


    <span class="flex">
      <h4 class="title">Dropdown by reviews.reviewerName</h4>

      <eui-dropdown
        :data="data"
        displayField="reviews.reviewerName"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>


    <span class="flex">
      <h4 class="title">Default value</h4>

      <eui-dropdown
        :data="data"
        displayField="title"
        defaultValue="Red Nail Polish"
        @itemSelected="onProductSelected"
        styleValue="width: 25vw;"
        placeholder="Search products..."
      />
    </span>

  </div>
</template>

// ensemble-angular-web/src/app/dropdown.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
import { FakeDataService } from "./fake.api.service";
import { map } from "rxjs";
import { fakeProduct } from "./fakeData.const";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  standalone: true,
  template: `
    <div class="doc">
      <span class="flex">
        <h4 class="title">Dropdown by title</h4>
        <eui-dropdown
          [data]="data"
          displayField="title" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Dropdown by dimensions.height</h4>
        <eui-dropdown
          [data]="data"
          displayField="dimensions.height" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Dropdown by reviews.reviewerName</h4>
        <eui-dropdown
          [data]="data"
          displayField="reviews.reviewerName" 
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Defalut value</h4>
        <eui-dropdown
          [data]="data"
          displayField="title" 
          defaultValue="Red Nail Polish"
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
      <span class="flex">
        <h4 class="title">Compact - Defalut value</h4>
        <eui-dropdown
          [data]="data"
          [compact]="true"
          displayField="title" 
          defaultValue="Red Nail Polish"
          (itemSelected)="onProductSelected($event)"
          styleValue="width: 25vw;"
          placeholder="Search products..."
        />
      </span>
    </div>
    `
})
export class DropdownComponent {

  public data = fakeProduct.products;

  /**
   * This method will be called by the (itemSelected) event
   */
  onProductSelected(event: Event) {
    const product = (event as CustomEvent).detail;

    console.log('Product selected from Angular!', product);
    // Now you have the full object:
    // { id: 1, title: "Essence Mascara...", ... }
  }
}
