// ensemble-vue/src/pages/tab.vue
<script setup lang="ts">
import { EuiTab } from 'ensemble-ui/vue'

interface TabData {
  Title: string
  Icon?: string
  badgeCounter?: string
}

const data: TabData[] = [
  { Title: 'Personal info', Icon: 'user' },
  { Title: 'Stock data', Icon: 'arrow-trending-up' },
  { Title: 'Contact', Icon: 'phone', badgeCounter: '5' },
  { Title: 'Other info', Icon: 'ellipsis-horizontal' },
]
</script>

<template>
  <div class="doc">

    <span class="flex">
      <h4 class="title">TABS:</h4>

      <EuiTab :data="data" />
    </span>


    <span class="flex">
      <h4 class="title">TABS collapse:</h4>

      <EuiTab
        :data="data"
        collapse
      />
    </span>


    <span class="flex">
      <h4 class="title">TABS disabled:</h4>

      <EuiTab
        :data="data"
        disabled
      />
    </span>


    <span class="flex">
      <h4 class="title">TABS collapse and disabled:</h4>

      <EuiTab
        :data="data"
        collapse
        disabled
      />
    </span>

  </div>
</template>

// ensemble-docntest/src/app/tab.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";

@Component({
    selector: 'app-root',
    styleUrl: './app.scss',
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    standalone: true,
    template: `
    <div class="doc">
        <span class="flex">
            <h4 class="title">TABS:</h4>
            <eui-tab [data]="data"/>
        </span>
    </div>
    `
})
export class TabComponent {
    data: TabData[] = [
        { Title: "Personal info", Icon: "user" },
        { Title: "Stock data", Icon: "arrow-trending-up" },
        { Title: "Contact", Icon: "phone", badgeCounter: "5" },
        { Title: "Other info", Icon: "ellipsis-horizontal" }
    ]
}

export interface TabData {
    Title: string,
    Icon?: string,
    badgeCounter?: string
}
