// ensemble-angular/src/app/button.component.ts
import { Component } from "@angular/core";
import { EuiButton } from "ensemble-ui/angular";

@Component({
  selector: 'app-root',
  styleUrl: './app.scss',
  imports: [EuiButton],
  standalone: true,
  template: `
    <div class="doc">
        <span class="flex">
        <h4 class="title">primary - normal buttons:</h4>
        <eui-button size='sm' variant='primary'>Small Primary</eui-button>
        <eui-button size='md' variant='primary'>Medium Primary</eui-button>
        <eui-button size='lg' variant='primary'>large Primary</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">success - normal buttons:</h4>
        <eui-button size='sm' variant='success'>Small success</eui-button>
        <eui-button size='md' variant='success'>Medium success</eui-button>
        <eui-button size='lg' variant='success'>large success</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">info - normal buttons:</h4>
        <eui-button size='sm' variant='info'>Small info</eui-button>
        <eui-button size='md' variant='info'>Medium info</eui-button>
        <eui-button size='lg' variant='info'>large info</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">warning - normal buttons:</h4>
        <eui-button size='sm' variant='warning'>Small warning</eui-button>
        <eui-button size='md' variant='warning'>Medium warning</eui-button>
        <eui-button size='lg' variant='warning'>large warning</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">danger - normal buttons:</h4>
        <eui-button size='sm' variant='danger'>Small danger</eui-button>
        <eui-button size='md' variant='danger'>Medium danger</eui-button>
        <eui-button size='lg' variant='danger'>large danger</eui-button>
          </span>
          <span class="divider"></span>
          <span class="flex">
        <h4 class="title">primary - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='primary'>Small Primary</eui-button>
        <eui-button mode='outline' size='md' variant='primary'>Medium Primary</eui-button>
        <eui-button mode='outline' size='lg' variant='primary'>large Primary</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">success - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='success'>Small success</eui-button>
        <eui-button mode='outline' size='md' variant='success'>Medium success</eui-button>
        <eui-button mode='outline' size='lg' variant='success'>large success</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">info - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='info'>Small info</eui-button>
        <eui-button mode='outline' size='md' variant='info'>Medium info</eui-button>
        <eui-button mode='outline' size='lg' variant='info'>large success</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">info - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='info'>Small info</eui-button>
        <eui-button mode='outline' size='md' variant='info'>Medium info</eui-button>
        <eui-button mode='outline' size='lg' variant='info'>large info</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">warning - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='warning'>Small warning</eui-button>
        <eui-button mode='outline' size='md' variant='warning'>Medium warning</eui-button>
        <eui-button mode='outline' size='lg' variant='warning'>large warning</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">danger - outline buttons:</h4>
        <eui-button mode='outline' size='sm' variant='danger'>Small danger</eui-button>
        <eui-button mode='outline' size='md' variant='danger'>Medium danger</eui-button>
        <eui-button mode='outline' size='lg' variant='danger'>large danger</eui-button>
          </span>
          <span class="divider"></span>
          <span class="flex">
        <h4 class="title">primary - text-button buttons:</h4>
        <eui-button mode='text-button' size='sm' variant='primary'>Small Primary</eui-button>
        <eui-button mode='text-button' size='md' variant='primary'>Medium Primary</eui-button>
        <eui-button mode='text-button' size='lg' variant='primary'>large Primary</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">success - text-button buttons:</h4>
        <eui-button mode='text-button' size='sm' variant='success'>Small success</eui-button>
        <eui-button mode='text-button' size='md' variant='success'>Medium success</eui-button>
        <eui-button mode='text-button' size='lg' variant='success'>large success</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">info - text-button buttons:</h4>
        <eui-button mode='text-button' size='sm' variant='info'>Small info</eui-button>
        <eui-button mode='text-button' size='md' variant='info'>Medium info</eui-button>
        <eui-button mode='text-button' size='lg' variant='info'>large info</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">warning - text-button buttons:</h4>
        <eui-button mode='text-button' size='sm' variant='warning'>Small warning</eui-button>
        <eui-button mode='text-button' size='md' variant='warning'>Medium warning</eui-button>
        <eui-button mode='text-button' size='lg' variant='warning'>large warning</eui-button>
          </span>
          <span class="flex">
        <h4 class="title">danger - text-button buttons:</h4>
        <eui-button mode='text-button' size='sm' variant='danger'>Small danger</eui-button>
        <eui-button mode='text-button' size='md' variant='danger'>Medium danger</eui-button>
        <eui-button mode='text-button' size='lg' variant='danger'>large danger</eui-button>
          </span>
                    <span class="flex">
        <h4 class="title">neutral buttons:</h4>
        <eui-button variant='neutral'>Small neutral</eui-button>
        <eui-button variant='neutral'>Medium neutral</eui-button>
        <eui-button variant='neutral'>large neutral</eui-button>
          </span>
          <span class="divider"></span>
          <span class="flex">
        <h4 class="title">primary - text-button buttons:</h4>
        <eui-button disabled="true">Small Primary</eui-button>
        <eui-button disabled="true">Medium Primary</eui-button>
        <eui-button disabled="true">large Primary</eui-button>
          </span>

    </div>
    `
})
export class ButtonComponent { }

// ensemble-ui/src/components/button/button.tsx
import { Component, Prop, h, Host, Element } from '@stencil/core';

@Component({
  tag: 'eui-button',
  styleUrl: "./button.scss",
  shadow: false,
})
export class EUIButton {
  @Element() hostEl!: HTMLElement;

  @Prop() styleValue?: string;
  @Prop() size: "sm" | "md" | "lg" = "md";
  @Prop() variant: 'primary' | 'danger' | 'success' | 'warning' | 'neutral' = 'primary';
  @Prop() mode: "normal" | "outline" | "text-button" = "normal";

  componentWillLoad() {
    if (this.styleValue) {
      this.hostEl.setAttribute('style', this.styleValue);
    }
  }

  render() {

    const attrs = Array.from(this.hostEl.attributes)
      .filter(attr => !['size', 'variant', 'mode', 'class'].includes(attr.name))
      .reduce((acc, attr) => {
        acc[attr.name] = attr.value;
        return acc;
      }, {} as Record<string, string>);

    return (
      <Host>
        <button
          {...attrs}
          class={{
            btn: true,
            [`btn--${this.size}`]: true,
            [`btn--${this.variant}`]: true,
            [`btn--${this.mode}`]: true,
          }}
        >
          <slot />
        </button>
      </Host>
    );
  }
}
